# Generated by Django 5.2.12 on 2026-03-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_growth_crm_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('site', 'site'), ('tg', 'tg')], default='site', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadevent',
            name='source',
            field=models.CharField(blank=True, default='site', max_length=50),
        ),
    ]
