# Generated by Django 5.2.12 on 2026-03-21 04:43

import django.db.models.deletion
from django.db import migrations, models


def seed_workflow_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')

    for order in Order.objects.all().iterator():
        if order.status == 'canceled' or order.stage == 'cancelled':
            workflow = 'canceled'
        elif order.status == 'done' or order.stage == 'completed':
            workflow = 'delivered'
        elif order.status == 'paid' or order.stage == 'paid':
            workflow = 'paid'
        elif order.status == 'in_work' or order.stage == 'in_progress':
            workflow = 'confirmed'
        else:
            workflow = 'new'
        order.workflow_status = workflow
        order.save(update_fields=['workflow_status'])
        OrderStatusHistory.objects.create(order=order, status=workflow, comment='История добавлена миграцией')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_lead_source_alter_leadevent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending_payment', 'Ожидает оплату'), ('paid', 'Оплачен'), ('confirmed', 'Подтверждён'), ('assembling', 'Собирается'), ('delivering', 'В доставке'), ('delivered', 'Доставлен'), ('canceled', 'Отменён'), ('refunded', 'Возврат')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
                ('reserved_count', models.PositiveSmallIntegerField(default=0)),
                ('same_day_only', models.BooleanField(default=False)),
                ('delivery_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='orders.deliveryoption')),
            ],
            options={
                'ordering': ['date', 'time_from', 'id'],
                'unique_together': {('delivery_option', 'date', 'time_from', 'time_to')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryslot'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending_payment', 'Ожидает оплату'), ('paid', 'Оплачен'), ('confirmed', 'Подтверждён'), ('assembling', 'Собирается'), ('delivering', 'В доставке'), ('delivered', 'Доставлен'), ('canceled', 'Отменён'), ('refunded', 'Возврат')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(seed_workflow_statuses, migrations.RunPython.noop),
    ]
