# Generated by Django 5.2.14 on 2026-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('short_description', models.CharField(max_length=320)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Funded'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('location', models.CharField(blank=True, max_length=160)),
                ('beneficiaries_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='projects_pr_status_2cea5d_idx'), models.Index(fields=['slug'], name='projects_pr_slug_042165_idx')],
            },
        ),
    ]
