# Generated by Django 5.2.14 on 2026-05-13 10:15

import apps.donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('donor_name', models.CharField(blank=True, max_length=180)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('USDT', 'USDT')], default='USD', max_length=8)),
                ('method', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mir', 'Mir'), ('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt_trc20', 'USDT TRC20'), ('usdt_erc20', 'USDT ERC20'), ('cash', 'Cash')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('receipt_upload', models.FileField(blank=True, null=True, upload_to=apps.donations.models.receipt_upload_path)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/pdf/')),
                ('payment_reference', models.CharField(blank=True, max_length=80, unique=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('suspicious_reason', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('manual_bank', 'Manual bank verification'), ('crypto', 'Crypto transfer'), ('cash', 'Cash handover')], max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
