# Generated by Django 5.2.14 on 2026-05-13 10:22

import apps.donations.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('method', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mir', 'Mir'), ('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt_trc20', 'USDT TRC20'), ('usdt_erc20', 'USDT ERC20'), ('cash', 'Cash')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('purpose', models.CharField(max_length=220)),
                ('comment', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('suspicious_score', models.PositiveSmallIntegerField(default=0)),
                ('suspicious_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual_card', 'Manual card verification'), ('crypto', 'Crypto'), ('cash', 'Cash')], max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.donations.models.donation_receipt_path)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=apps.donations.models.donation_receipt_path)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
