# Generated by Django 5.2.14 on 2026-05-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='donation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='donations.donation'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['reference'], name='donations_d_referen_733100_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'created_at'], name='donations_d_status_ad9788_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['method', 'status'], name='donations_d_method_e5e9ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='donationallocation',
            unique_together={('donation', 'project')},
        ),
    ]
