# Generated by Django 5.2.14 on 2026-05-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='donations.donation'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'method'], name='donations_d_status_29a1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['public_id'], name='donations_d_public__536961_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway', 'status'], name='donations_t_gateway_8e70ea_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_id'], name='donations_t_externa_32c016_idx'),
        ),
    ]
