# Generated by Django 5.2.10 on 2026-01-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Atrium Art', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Магазин цветов, товары для праздника, доставка букетов', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='+7 (982) 726-84-00', max_length=50)),
                ('address', models.CharField(blank=True, default='Свердловская область, Екатеринбург, ул. Краснолесья, 10/3', max_length=300)),
                ('tg_url', models.URLField(blank=True, default='https://t.me/atrium_art')),
                ('vk_url', models.URLField(blank=True, default='https://vk.com/public211403983')),
                ('maps_url', models.URLField(blank=True, default='')),
                ('work_hours', models.CharField(blank=True, default='Пн–Вс 09:00–21:00', max_length=100)),
                ('yandex_rating', models.DecimalField(decimal_places=1, default=4.6, max_digits=3)),
                ('yandex_reviews_count', models.PositiveIntegerField(default=22)),
            ],
        ),
    ]
