# Generated by Django 5.2.10 on 2026-01-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='maps_url',
            field=models.URLField(blank=True, default='https://yandex.ru/profile/7437735476?lang=ru&no-distribution=1&view-state=mini&source=wizbiz_new_map_single'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='name',
            field=models.CharField(default='Цветочный Atrium', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='tg_url',
            field=models.URLField(blank=True, default='https://t.me/CHANGE_ME'),
        ),
    ]
