server {
    listen 80;
    server_name цветы.online xn--b1ag3bn2a.online www.цветы.online www.xn--b1ag3bn2a.online;

    client_max_body_size 25m;

    location /static/ {
        alias /home/atrium/app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias /home/atrium/app/media/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
