# Generated by Django 5.2.14 on 2026-05-13 11:15

import apps.core.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', apps.core.fields.EncryptedTextField()),
                ('phone', apps.core.fields.EncryptedTextField(blank=True)),
                ('email', apps.core.fields.EncryptedTextField(blank=True)),
                ('inn', apps.core.fields.EncryptedTextField(blank=True)),
                ('normalized_full_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('inn_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_summary', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('legal_recommendations', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_checks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='checks.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankruptcyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Публичная кадастровая карта'), ('tax', 'Налоговые данные'), ('enforcement', 'Исполнительные производства'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('telegram_forums', 'Telegram/форумы'), ('problem_developers', 'Проблемные застройщики'), ('fraud_registries', 'Базы мошенников'), ('media', 'Новости и СМИ')], default='efrsb', max_length=64)),
                ('debtor_name', models.CharField(blank=True, max_length=255)),
                ('inn_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('case_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('stage', models.CharField(blank=True, max_length=128)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('property_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcy_records', to='checks.check')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Публичная кадастровая карта'), ('tax', 'Налоговые данные'), ('enforcement', 'Исполнительные производства'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('telegram_forums', 'Telegram/форумы'), ('problem_developers', 'Проблемные застройщики'), ('fraud_registries', 'Базы мошенников'), ('media', 'Новости и СМИ')], default='courts', max_length=64)),
                ('case_number', models.CharField(db_index=True, max_length=128)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('filed_at', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('property_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_cases', to='checks.check')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Публичная кадастровая карта'), ('tax', 'Налоговые данные'), ('enforcement', 'Исполнительные производства'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('telegram_forums', 'Telegram/форумы'), ('problem_developers', 'Проблемные застройщики'), ('fraud_registries', 'Базы мошенников'), ('media', 'Новости и СМИ')], default='fssp', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creditor', models.CharField(blank=True, max_length=255)),
                ('proceeding_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('property_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='checks.check')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('normalized_address', models.TextField(blank=True, db_index=True)),
                ('cadastral_number', models.CharField(db_index=True, max_length=64)),
                ('region', models.CharField(blank=True, db_index=True, max_length=128)),
                ('property_type', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'indexes': [models.Index(fields=['cadastral_number'], name='checks_prop_cadastr_5bfbc2_idx'), models.Index(fields=['region', 'created_at'], name='checks_prop_region_d2cc44_idx')],
            },
        ),
        migrations.AddField(
            model_name='check',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='checks.property'),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Публичная кадастровая карта'), ('tax', 'Налоговые данные'), ('enforcement', 'Исполнительные производства'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('telegram_forums', 'Telegram/форумы'), ('problem_developers', 'Проблемные застройщики'), ('fraud_registries', 'Базы мошенников'), ('media', 'Новости и СМИ')], max_length=64)),
                ('category', models.CharField(db_index=True, max_length=128)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=32)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('property_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='checks.check')),
            ],
            options={
                'ordering': ['-score', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedAd',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Публичная кадастровая карта'), ('tax', 'Налоговые данные'), ('enforcement', 'Исполнительные производства'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('telegram_forums', 'Telegram/форумы'), ('problem_developers', 'Проблемные застройщики'), ('fraud_registries', 'Базы мошенников'), ('media', 'Новости и СМИ')], max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('address', models.TextField(blank=True)),
                ('seller_phone_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('property_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_ads', to='checks.check')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParserResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Публичная кадастровая карта'), ('tax', 'Налоговые данные'), ('enforcement', 'Исполнительные производства'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('telegram_forums', 'Telegram/форумы'), ('problem_developers', 'Проблемные застройщики'), ('fraud_registries', 'Базы мошенников'), ('media', 'Новости и СМИ')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('empty', 'Empty'), ('failed', 'Failed'), ('captcha_required', 'Captcha required'), ('rate_limited', 'Rate limited')], max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('evidence_url', models.URLField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('property_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_results', to='checks.check')),
            ],
            options={
                'ordering': ['source', '-created_at'],
                'indexes': [models.Index(fields=['source', 'status', 'created_at'], name='checks_pars_source_0df934_idx')],
                'unique_together': {('property_check', 'source')},
            },
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['status', 'created_at'], name='checks_chec_status_e7d399_idx'),
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['risk_score'], name='checks_chec_risk_sc_7f92cf_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['severity', 'category'], name='checks_risk_severit_554a22_idx'),
        ),
    ]
