# Generated by Django 6.0.5 on 2026-05-13 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('cadastral_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Кадастровый номер')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ИНН')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'В работе'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='low', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('rf_courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Кадастровая карта'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('news', 'Новости и СМИ'), ('telegram', 'Telegram'), ('developers', 'Проблемные застройщики')], max_length=32)),
                ('case_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('participant', models.CharField(blank=True, max_length=255)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_request', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='court_cases', to='checks.check')),
            ],
            options={
                'verbose_name': 'Судебное дело',
                'verbose_name_plural': 'Судебные дела',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('rf_courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Кадастровая карта'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('news', 'Новости и СМИ'), ('telegram', 'Telegram'), ('developers', 'Проблемные застройщики')], max_length=32)),
                ('debtor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proceeding_number', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_request', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='checks.check')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ownership_share', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_request', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='checks.check')),
            ],
            options={
                'verbose_name': 'Собственник',
                'verbose_name_plural': 'Собственники',
            },
        ),
        migrations.CreateModel(
            name='ParserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('rf_courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Кадастровая карта'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('news', 'Новости и СМИ'), ('telegram', 'Telegram'), ('developers', 'Проблемные застройщики')], max_length=32)),
                ('status', models.CharField(default='success', max_length=16)),
                ('matched', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('check_request', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='parser_results', to='checks.check')),
            ],
            options={
                'verbose_name': 'Результат парсера',
                'verbose_name_plural': 'Результаты парсеров',
                'ordering': ('source',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=512)),
                ('cadastral_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, max_length=128)),
                ('registration_status', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_request', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='checks.check')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, choices=[('fssp', 'ФССП'), ('efrsb', 'ЕФРСБ'), ('kad_arbitr', 'КАД Арбитр'), ('rf_courts', 'Суды РФ'), ('rosreestr', 'Росреестр'), ('cadastral_map', 'Кадастровая карта'), ('avito', 'Avito'), ('cian', 'Cian'), ('domclick', 'Domclick'), ('news', 'Новости и СМИ'), ('telegram', 'Telegram'), ('developers', 'Проблемные застройщики')], max_length=32)),
                ('level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=16)),
                ('score', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('check_request', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='checks.check')),
            ],
            options={
                'verbose_name': 'Риск',
                'verbose_name_plural': 'Риски',
                'ordering': ('-score', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['status', 'created_at'], name='checks_chec_status_e7d399_idx'),
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['risk_level', 'risk_score'], name='checks_chec_risk_le_503de6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parserresult',
            unique_together={('check_request', 'source')},
        ),
    ]
