# Generated by Django 6.0.5 on 2026-05-13 11:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=512)),
                ('cadastral_number', models.CharField(blank=True, max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('inn', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('running', 'В работе'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Итоговая оценка риска от 0 до 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('report_html', models.TextField(blank=True)),
                ('report_pdf', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=128)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('participant', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('filed_at', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verification', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='court_cases', to='checks.check')),
            ],
            options={
                'db_table': 'court_cases',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proceeding_number', models.CharField(blank=True, max_length=128)),
                ('bailiff_department', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verification', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='checks.check')),
            ],
            options={
                'db_table': 'debts',
            },
        ),
        migrations.CreateModel(
            name='ParserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('empty', 'Нет данных'), ('failed', 'Ошибка'), ('cached', 'Из кэша')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('matched_fields', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('cache_key', models.CharField(blank=True, max_length=128)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='parser_results', to='checks.check')),
            ],
            options={
                'db_table': 'parser_results',
                'ordering': ('source',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=512)),
                ('cadastral_number', models.CharField(blank=True, max_length=128)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verification', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='checks.check')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verification', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='checks.check')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='checks.property')),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], max_length=16)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('parser_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='checks.parserresult')),
                ('verification', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='checks.check')),
            ],
            options={
                'db_table': 'risks',
                'ordering': ('-weight', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['status', '-created_at'], name='checks_status_012c60_idx'),
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['cadastral_number'], name='checks_cadastr_a9f192_idx'),
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['inn'], name='checks_inn_febd28_idx'),
        ),
        migrations.AddIndex(
            model_name='courtcase',
            index=models.Index(fields=['case_number'], name='court_cases_case_nu_feac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='courtcase',
            index=models.Index(fields=['participant'], name='court_cases_partici_ca4235_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['debtor_name'], name='debts_debtor__44d62f_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['proceeding_number'], name='debts_proceed_459f28_idx'),
        ),
        migrations.AddIndex(
            model_name='parserresult',
            index=models.Index(fields=['source', 'status'], name='parser_resu_source_2a6614_idx'),
        ),
        migrations.AddIndex(
            model_name='parserresult',
            index=models.Index(fields=['verification', 'source'], name='parser_resu_check_i_adfd38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parserresult',
            unique_together={('verification', 'source')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['cadastral_number'], name='properties_cadastr_b9887f_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['full_name'], name='owners_full_na_cdd772_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['inn'], name='owners_inn_a9f23f_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['verification', 'severity'], name='risks_check_i_3d9759_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['code'], name='risks_code_4d548b_idx'),
        ),
    ]
