# Generated by Django 5.2.14 on 2026-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, max_length=160)),
                ('network', models.CharField(max_length=16)),
                ('expected_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('confirmations', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting_tx', 'Waiting transaction'), ('detected', 'Detected'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='waiting_tx', max_length=24)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT')], max_length=8)),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('erc20', 'ERC20'), ('trc20', 'TRC20')], max_length=16)),
                ('address', models.CharField(max_length=160, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('min_confirmations', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['currency', 'network'],
            },
        ),
    ]
