# Generated by Django 5.2.14 on 2026-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, max_length=180)),
                ('expected_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for transfer'), ('detected', 'Transfer detected'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='waiting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('network', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('trc20', 'TRON TRC20'), ('erc20', 'Ethereum ERC20')], max_length=16)),
                ('currency', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=160, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='crypto-wallets/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['currency', 'network'],
            },
        ),
    ]
