# Generated by Django 5.2.14 on 2026-05-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto_payments', '0001_initial'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopayment',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payment', to='donations.donation'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('currency', 'network', 'address')},
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crypto_payments.cryptowallet'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['tx_hash'], name='crypto_paym_tx_hash_48cd26_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['status'], name='crypto_paym_status_5e2d71_idx'),
        ),
    ]
