# Generated by Django 5.2.14 on 2026-05-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmeeting',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashmeeting',
            index=models.Index(fields=['city', 'status'], name='cash_reques_city_ad1737_idx'),
        ),
    ]
